"""Add custom_billing fields to subscription

Revision ID: 46fc4d453162
Revises: cbdc87fda027
Create Date: 2026-02-27 15:32:35.233554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fc4d453162'
down_revision: Union[str, Sequence[str], None] = 'cbdc87fda027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS custom_billing_amount INTEGER")
        op.execute("ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS custom_billing_unit VARCHAR(20)")
    else:
        with op.batch_alter_table('subscriptions') as batch_op:
            batch_op.add_column(sa.Column('custom_billing_amount', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('custom_billing_unit', sa.String(length=20), nullable=True))
    
    # Add new ENUM value for postgres specifically using an isolated autocommit connection
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        url = bind.engine.url
        engine = sa.create_engine(url, isolation_level="AUTOCOMMIT")
        try:
            with engine.connect() as conn:
                conn.execute(sa.text("ALTER TYPE billingcycle ADD VALUE IF NOT EXISTS 'custom'"))
                print("Successfully added 'custom' to billingcycle ENUM.")
        except Exception as e:
            print(f"Warning: Could not alter billingcycle ENUM reliably: {e}")
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'custom_billing_unit')
    op.drop_column('subscriptions', 'custom_billing_amount')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
