"""Add custom_billing fields to subscription

Revision ID: 46fc4d453162
Revises: cbdc87fda027
Create Date: 2026-02-27 15:32:35.233554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fc4d453162'
down_revision: Union[str, Sequence[str], None] = 'cbdc87fda027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('custom_billing_amount', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('custom_billing_unit', sa.String(length=20), nullable=True))
    
    # Add new ENUM value for postgres specifically
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("ALTER TYPE billingcycle ADD VALUE IF NOT EXISTS 'custom'")
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'custom_billing_unit')
    op.drop_column('subscriptions', 'custom_billing_amount')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
