"""Initial migration

Revision ID: f8786e110844
Revises: 
Create Date: 2026-01-09 16:26:28.300382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8786e110844'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('CATEGORY', 'GROUP', 'CUSTOMER', 'SUBSCRIPTION', name='entitytype'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('CATEGORY', 'GROUP', 'CUSTOMER', 'SUBSCRIPTION', name='entitytype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_decision', sa.Enum('ACCEPTED', 'REJECTED', name='userdecision'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_created_at'), 'links', ['created_at'], unique=False)
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_source_id'), 'links', ['source_id'], unique=False)
    op.create_index(op.f('ix_links_source_type'), 'links', ['source_type'], unique=False)
    op.create_index(op.f('ix_links_target_id'), 'links', ['target_id'], unique=False)
    op.create_index(op.f('ix_links_target_type'), 'links', ['target_type'], unique=False)
    op.create_index(op.f('ix_links_user_decision'), 'links', ['user_decision'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_category_id'), 'groups', ['category_id'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_category_id'), 'customers', ['category_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_group_id'), 'customers', ['group_id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'WEEKLY', 'BIANNUAL', name='billingcycle'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_renewal_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'PAUSED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_category_id'), 'subscriptions', ['category_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_renewal_date'), 'subscriptions', ['next_renewal_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_vendor_name'), 'subscriptions', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_vendor_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_renewal_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_category_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_group_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_category_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_category_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_links_user_decision'), table_name='links')
    op.drop_index(op.f('ix_links_target_type'), table_name='links')
    op.drop_index(op.f('ix_links_target_id'), table_name='links')
    op.drop_index(op.f('ix_links_source_type'), table_name='links')
    op.drop_index(op.f('ix_links_source_id'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_index(op.f('ix_links_created_at'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
